// B0 — manifest migration. PARENT-OWNED.
//
// Every world already generated by the deployed service is a C1 v1.0 world. They
// must keep loading, so V3 is a superset reachable by a lossless upgrade rather
// than a break. Nothing is invented during migration: a field the v1 world never
// had becomes an explicit null or an empty list, and the fact that the world was
// migrated is recorded in expansion.compatibility.migrated_from.
import { emptyManifest, MANIFEST_VERSION, validateManifest } from "./schema.mjs";

const num = (v, d = 0) => (typeof v === "number" && isFinite(v) ? v : d);

function vec3(t) {
  if (!t) return { x: 0, y: 0, z: 0 };
  if (typeof t.x === "number" || typeof t.y === "number" || typeof t.z === "number") {
    return { x: num(t.x), y: num(t.y), z: num(t.z) };
  }
  if (t.position) return vec3(t.position);
  return { x: 0, y: 0, z: 0 };
}

/** Is this already a v3 manifest? */
export function isV3(m) {
  return !!(m && typeof m.manifest_version === "string" && /^3\./.test(m.manifest_version));
}

/**
 * Upgrade a C1 v1.0 world (or the runtime-augmented variant the deployed service
 * emits) to WorldManifestV3.
 *
 * @param {object} v1 the legacy world
 * @param {{worldVersion?:number, creatorId?:string}} opts
 */
export function migrateToV3(v1, { worldVersion = 1, creatorId = null } = {}) {
  if (isV3(v1)) return v1;
  if (!v1 || typeof v1 !== "object") throw new TypeError("migrateToV3 needs a v1 world object");

  const m = emptyManifest({
    worldId: v1.world_id || v1.worldId || "unknown",
    title: v1.meta?.title || "Untitled World",
    creatorId: creatorId ?? v1.meta?.creator_id ?? null,
    seed: num(v1.meta?.seed, 0),
  });

  m.world_version = worldVersion;
  m.meta = {
    ...m.meta,
    title: v1.meta?.title || m.meta.title,
    prompt: v1.meta?.prompt ?? null,
    genre: v1.meta?.genre ?? null,
    style: v1.meta?.style ?? v1.meta?.genre ?? null,
    creator_id: creatorId ?? v1.meta?.creator_id ?? null,
    created_at: v1.meta?.created_at || m.meta.created_at,
    maturity: v1.meta?.maturity || "13+",
  };

  // ---- environment: the v1 render block, where the seeder produced one -----
  const env = v1.environment || v1.env || {};
  m.environment = {
    ...m.environment,
    time_of_day: typeof env.time_of_day === "number" ? env.time_of_day : m.environment.time_of_day,
    weather: env.weather || "clear",
    sky: env.sky ?? null,
    fog: env.fog ?? null,
    ambient_light: env.ambient ?? env.ambient_light ?? null,
    directional_light: env.dir ?? env.directional_light ?? null,
  };

  // ---- terrain -------------------------------------------------------------
  if (v1.terrain) {
    const kind = v1.terrain.type === "heightmap" ? "heightmap" : v1.terrain.type === "tilegrid" ? "tilegrid" : "flat";
    m.terrain = {
      kind,
      size: { w: num(v1.terrain.size?.w, 128), h: num(v1.terrain.size?.h, 128) },
      data: v1.terrain.data ?? null,
      materials: v1.terrain.material ? [v1.terrain.material] : [],
    };
  }

  // ---- zones: v1 kept them inside terrain ---------------------------------
  const v1zones = v1.terrain?.zones || v1.zones || [];
  m.zones = v1zones.map((z, i) => {
    const rect = z.rect || z.bounds || [];
    const bounds = rect.length === 4 ? rect.map((n) => num(n)) : [0, 0, num(m.terrain.size.w), num(m.terrain.size.h)];
    return {
      id: z.id || `zone_${(z.name || i).toString().toLowerCase().replace(/[^a-z0-9]+/g, "_")}`,
      name: z.name || z.id || `Zone ${i + 1}`,
      kind: "district",
      bounds,
      parent_zone: null,
      tags: [],
      ambience: null,
    };
  });

  // ---- assets: v1 had no registry, so one is derived from the kinds used ---
  const kinds = new Map();
  const kindOf = (k, fallbackKind) => {
    const key = String(k || fallbackKind || "prop");
    if (!kinds.has(key)) {
      kinds.set(key, {
        id: `asset_${key.replace(/[^a-zA-Z0-9]+/g, "_")}`,
        kind: key.startsWith("building") ? "building"
          : key.startsWith("vehicle") ? "vehicle"
          : key.startsWith("npc") || fallbackKind === "character" ? "character"
          : key.startsWith("item") ? "prop" : (fallbackKind || "prop"),
        format: "primitive",
        // The v1 worlds really were boxes and cylinders. Recording that honestly
        // is what lets B2/B3 measurably improve on it.
        primitive: { shape: "box", size: { x: 1, y: 1, z: 1 } },
        collision: { kind: "box", solid: true },
        lod: [],
        license: null,
        provenance: { migrated_from: "c1-v1.0-primitive" },
      });
    }
    return kinds.get(key).id;
  };

  // ---- structures (v1 objects) --------------------------------------------
  m.structures = (v1.objects || []).map((o, i) => ({
    id: o.object_id || `struct_${i}`,
    zone: null,
    asset_ref: kindOf(o.kind, "prop"),
    transform: {
      position: vec3(o.transform),
      rotation: { x: 0, y: num(o.transform?.rot), z: 0 },
      scale: { x: num(o.transform?.scale, 1), y: num(o.transform?.scale, 1), z: num(o.transform?.scale, 1) },
    },
    interactable: !!o.interactable,
    owner_id: o.owner_id ?? null,
    footprint: null,
    portals: [],
  }));

  // ---- npcs ----------------------------------------------------------------
  m.npcs = (v1.npcs || []).map((n, i) => ({
    id: n.npc_id || n.id || `npc_${i}`,
    name: n.name || n.kind || `NPC ${i + 1}`,
    role: n.kind || null,
    zone: null,
    spawn: vec3(n.spawn),
    asset_ref: kindOf(`npc.${n.kind || "generic"}`, "character"),
    behavior_ref: null,
    dialogue: n.dialogue_seed ? { seed: n.dialogue_seed, lines: [] } : { seed: null, lines: [] },
    schedule: [],
    faction: null,
    stats: null,
  }));

  // ---- items ---------------------------------------------------------------
  m.items = (v1.items || []).map((it, i) => ({
    id: it.item_id || it.id || `item_${i}`,
    name: it.name || it.kind || `Item ${i + 1}`,
    kind: it.kind || "misc",
    asset_ref: kindOf(`item.${it.kind || "generic"}`, "prop"),
    stackable: !!it.stackable,
    effects: [],
  }));

  const npcIds = new Set(m.npcs.map((n) => n.id));
  const itemIds = new Set(m.items.map((it) => it.id));
  const structIds = new Set(m.structures.map((s) => s.id));
  const zoneIds = new Set(m.zones.map((z) => z.id));
  const resolves = (t) => npcIds.has(t) || itemIds.has(t) || structIds.has(t) || zoneIds.has(t);

  // ---- quests --------------------------------------------------------------
  m.quests = (v1.quests || []).map((q, i) => ({
    id: q.quest_id || q.id || `quest_${i}`,
    title: q.title || `Quest ${i + 1}`,
    giver_npc: npcIds.has(q.giver) ? q.giver : null,
    zone: null,
    steps: (q.objectives || q.steps || []).map((o, j) => {
      // Only keep a target that actually resolves. A dangling target would make
      // the quest undoable, and inventing one would hide that from the critic.
      const raw = o.target || o.trigger || null;
      return {
        id: o.id || `step_${j}`,
        kind: mapStepKind(o.trigger || o.kind),
        target: resolves(raw) ? raw : null,
        description: o.text || o.description || null,
      };
    }),
    rewards: q.reward ? [q.reward] : [],
    prerequisites: [],
  }));

  m.assets = Array.from(kinds.values());

  // ---- provenance ----------------------------------------------------------
  m.provenance = {
    generated_by: [{
      lane: "world_architect",
      provider: v1.meta?.generated_by || "legacy-c1-seeder",
      model: v1.meta?.model || null,
      status: "AVAILABLE",
      at: v1.meta?.created_at || new Date().toISOString(),
      note: "recorded during v1 to v3 migration; the original generator is not re-run",
    }],
    source_prompt_hash: null,
    manifest_hash: null,
  };

  m.expansion = {
    history: [],
    compatibility: { min_runtime: "3.0.0", migrated_from: v1.schema_version || "1.0" },
  };

  // ---- spawn ---------------------------------------------------------------
  const playerSpawns = (v1.spawns || []).filter((s) => !s.role || s.role === "player");
  if (playerSpawns.length) {
    m.spawn.player_spawns = playerSpawns.map((s, i) => ({
      id: s.id || `spawn_${i}`,
      position: vec3(s),
      zone: null,
    }));
  }

  // Carry any atlas receipt already attached, without re-asserting verification.
  if (v1.meta?.atlas_receipt_hash) {
    m.meta.atlas_receipt_hash = v1.meta.atlas_receipt_hash;
    m.meta.atlas_signed = !!v1.meta.atlas_signed;
  }

  return m;
}

function mapStepKind(t) {
  const s = String(t || "").toLowerCase();
  if (/talk|speak|dialog/.test(s)) return "talk";
  if (/collect|gather|pick/.test(s)) return "collect";
  if (/deliver|give|return/.test(s)) return "deliver";
  if (/kill|defeat|destroy/.test(s)) return "defeat";
  if (/activate|use|switch|open/.test(s)) return "activate";
  if (/survive|hold/.test(s)) return "survive";
  if (/escort|protect/.test(s)) return "escort";
  if (/solve|puzzle/.test(s)) return "solve";
  return "reach";
}

/** Migrate if needed, then validate. Returns { manifest, migrated, validation }. */
export function ensureV3(world, opts = {}) {
  const migrated = !isV3(world);
  const manifest = migrated ? migrateToV3(world, opts) : world;
  return { manifest, migrated, validation: validateManifest(manifest) };
}

export { MANIFEST_VERSION };
